// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface CreateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 clientId = 1;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>int64 chambreId = 4;</code>
   * @return The chambreId.
   */
  long getChambreId();

  /**
   * <code>string prefernces = 5;</code>
   * @return The prefernces.
   */
  java.lang.String getPrefernces();
  /**
   * <code>string prefernces = 5;</code>
   * @return The bytes for prefernces.
   */
  com.google.protobuf.ByteString
      getPreferncesBytes();
}
