// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface GetAllClientsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllClientsRequest)
    com.google.protobuf.MessageOrBuilder {
}
