// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface GetClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  ma.ensaj.reservation.grpc.stubs.Client getClient();
  /**
   * <code>.Client client = 1;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ClientOrBuilder getClientOrBuilder();
}
