// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface GetChambreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetChambreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Chambre chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   * @return The chambre.
   */
  ma.ensaj.reservation.grpc.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ChambreOrBuilder getChambreOrBuilder();
}
