// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"\206\001\n\013Reservation\022\n\n\002i" +
      "d\030\001 \001(\003\022\021\n\tdateDebut\030\002 \001(\t\022\017\n\007dateFin\030\003 " +
      "\001(\t\022\027\n\006client\030\004 \001(\0132\007.Client\022\032\n\010chambres" +
      "\030\005 \001(\0132\010.Chambre\022\022\n\nprefrences\030\006 \001(\t\"S\n\006" +
      "Client\022\n\n\002id\030\001 \001(\003\022\013\n\003nom\030\002 \001(\t\022\016\n\006preno" +
      "m\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(" +
      "\t\"E\n\007Chambre\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 \001(\t\022\014" +
      "\n\004prix\030\003 \001(\001\022\022\n\ndisponible\030\004 \001(\010\"w\n\030Crea" +
      "teReservationRequest\022\020\n\010clientId\030\001 \001(\003\022\021" +
      "\n\tdateDebut\030\002 \001(\t\022\017\n\007dateFin\030\003 \001(\t\022\021\n\tch" +
      "ambreId\030\004 \001(\003\022\022\n\nprefernces\030\005 \001(\t\"8\n\031Cre" +
      "ateReservationResponse\022\n\n\002id\030\001 \001(\003\022\017\n\007me" +
      "ssage\030\002 \001(\t\"#\n\025GetReservationRequest\022\n\n\002" +
      "id\030\001 \001(\003\";\n\026GetReservationResponse\022!\n\013re" +
      "servation\030\001 \001(\0132\014.Reservation\"\203\001\n\030Update" +
      "ReservationRequest\022\n\n\002id\030\001 \001(\003\022\020\n\010client" +
      "Id\030\002 \001(\003\022\021\n\tdateDebut\030\003 \001(\t\022\017\n\007dateFin\030\004" +
      " \001(\t\022\021\n\tchambreId\030\005 \001(\003\022\022\n\nprefernces\030\006 " +
      "\001(\t\">\n\031UpdateReservationResponse\022!\n\013rese" +
      "rvation\030\001 \001(\0132\014.Reservation\"&\n\030DeleteRes" +
      "ervationRequest\022\n\n\002id\030\001 \001(\003\",\n\031DeleteRes" +
      "ervationResponse\022\017\n\007message\030\001 \001(\t\"\033\n\031Get" +
      "AllReservationsRequest\"@\n\032GetAllReservat" +
      "ionsResponse\022\"\n\014reservations\030\001 \003(\0132\014.Res" +
      "ervation\"R\n\024CreateChambreRequest\022\n\n\002id\030\001" +
      " \001(\003\022\014\n\004type\030\002 \001(\t\022\014\n\004prix\030\003 \001(\001\022\022\n\ndisp" +
      "onible\030\004 \001(\010\"4\n\025CreateChambreResponse\022\n\n" +
      "\002id\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\"\037\n\021GetChambre" +
      "Request\022\n\n\002id\030\001 \001(\003\"/\n\022GetChambreRespons" +
      "e\022\031\n\007chambre\030\001 \001(\0132\010.Chambre\"R\n\024UpdateCh" +
      "ambreRequest\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 \001(\t\022\014" +
      "\n\004prix\030\003 \001(\001\022\022\n\ndisponible\030\004 \001(\010\"C\n\025Upda" +
      "teChambreResponse\022\031\n\007chambre\030\001 \001(\0132\010.Cha" +
      "mbre\022\017\n\007message\030\002 \001(\t\"\"\n\024DeleteChambreRe" +
      "quest\022\n\n\002id\030\001 \001(\003\"(\n\025DeleteChambreRespon" +
      "se\022\017\n\007message\030\001 \001(\t\"\027\n\025GetAllChambresReq" +
      "uest\"4\n\026GetAllChambresResponse\022\032\n\010chambr" +
      "es\030\001 \003(\0132\010.Chambre\"`\n\023CreateClientReques" +
      "t\022\n\n\002id\030\001 \001(\003\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030\003 \001" +
      "(\t\022\r\n\005email\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"3\n\024" +
      "CreateClientResponse\022\n\n\002id\030\001 \001(\003\022\017\n\007mess" +
      "age\030\002 \001(\t\"\036\n\020GetClientRequest\022\n\n\002id\030\001 \001(" +
      "\003\",\n\021GetClientResponse\022\027\n\006client\030\001 \001(\0132\007" +
      ".Client\"`\n\023UpdateClientRequest\022\n\n\002id\030\001 \001" +
      "(\003\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030\003 \001(\t\022\r\n\005email" +
      "\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"@\n\024UpdateClien" +
      "tResponse\022\027\n\006client\030\001 \001(\0132\007.Client\022\017\n\007me" +
      "ssage\030\002 \001(\t\"!\n\023DeleteClientRequest\022\n\n\002id" +
      "\030\001 \001(\003\"\'\n\024DeleteClientResponse\022\017\n\007messag" +
      "e\030\001 \001(\t\"\026\n\024GetAllClientsRequest\"1\n\025GetAl" +
      "lClientsResponse\022\030\n\007clients\030\001 \003(\0132\007.Clie" +
      "nt2\212\003\n\022ReservationService\022J\n\021CreateReser" +
      "vation\022\031.CreateReservationRequest\032\032.Crea" +
      "teReservationResponse\022A\n\016GetReservation\022" +
      "\026.GetReservationRequest\032\027.GetReservation" +
      "Response\022J\n\021UpdateReservation\022\031.UpdateRe" +
      "servationRequest\032\032.UpdateReservationResp" +
      "onse\022J\n\021DeleteReservation\022\031.DeleteReserv" +
      "ationRequest\032\032.DeleteReservationResponse" +
      "\022M\n\022GetAllReservations\022\032.GetAllReservati" +
      "onsRequest\032\033.GetAllReservationsResponse2" +
      "\312\002\n\016ChambreService\022>\n\rCreateChambre\022\025.Cr" +
      "eateChambreRequest\032\026.CreateChambreRespon" +
      "se\0225\n\nGetChambre\022\022.GetChambreRequest\032\023.G" +
      "etChambreResponse\022>\n\rUpdateChambre\022\025.Upd" +
      "ateChambreRequest\032\026.UpdateChambreRespons" +
      "e\022>\n\rDeleteChambre\022\025.DeleteChambreReques" +
      "t\032\026.DeleteChambreResponse\022A\n\016GetAllChamb" +
      "res\022\026.GetAllChambresRequest\032\027.GetAllCham" +
      "bresResponse2\272\002\n\rClientService\022;\n\014Create" +
      "Client\022\024.CreateClientRequest\032\025.CreateCli" +
      "entResponse\0222\n\tGetClient\022\021.GetClientRequ" +
      "est\032\022.GetClientResponse\022;\n\014UpdateClient\022" +
      "\024.UpdateClientRequest\032\025.UpdateClientResp" +
      "onse\022;\n\014DeleteClient\022\024.DeleteClientReque" +
      "st\032\025.DeleteClientResponse\022>\n\rGetAllClien" +
      "ts\022\025.GetAllClientsRequest\032\026.GetAllClient" +
      "sResponseB#\n\037ma.ensaj.reservation.grpc.s" +
      "tubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "DateDebut", "DateFin", "Client", "Chambres", "Prefrences", });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientId", "DateDebut", "DateFin", "ChambreId", "Prefernces", });
    internal_static_CreateReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CreateReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationResponse_descriptor,
        new java.lang.String[] { "Id", "Message", });
    internal_static_GetReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "ClientId", "DateDebut", "DateFin", "ChambreId", "Prefernces", });
    internal_static_UpdateReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_CreateChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_CreateChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateChambreRequest_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
    internal_static_CreateChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CreateChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateChambreResponse_descriptor,
        new java.lang.String[] { "Id", "Message", });
    internal_static_GetChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_GetChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_GetChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_UpdateChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_UpdateChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateChambreRequest_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
    internal_static_UpdateChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_UpdateChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateChambreResponse_descriptor,
        new java.lang.String[] { "Chambre", "Message", });
    internal_static_DeleteChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_DeleteChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_DeleteChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GetAllChambresRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_GetAllChambresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllChambresResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_GetAllChambresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresResponse_descriptor,
        new java.lang.String[] { "Chambres", });
    internal_static_CreateClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_CreateClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateClientRequest_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_CreateClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_CreateClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateClientResponse_descriptor,
        new java.lang.String[] { "Id", "Message", });
    internal_static_GetClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_GetClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_GetClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_UpdateClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_UpdateClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateClientRequest_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_UpdateClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_UpdateClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateClientResponse_descriptor,
        new java.lang.String[] { "Client", "Message", });
    internal_static_DeleteClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_DeleteClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_DeleteClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GetAllClientsRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_GetAllClientsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllClientsResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_GetAllClientsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsResponse_descriptor,
        new java.lang.String[] { "Clients", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
