// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>.Client client = 4;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 4;</code>
   * @return The client.
   */
  ma.ensaj.reservation.grpc.stubs.Client getClient();
  /**
   * <code>.Client client = 4;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.Chambre chambres = 5;</code>
   * @return Whether the chambres field is set.
   */
  boolean hasChambres();
  /**
   * <code>.Chambre chambres = 5;</code>
   * @return The chambres.
   */
  ma.ensaj.reservation.grpc.stubs.Chambre getChambres();
  /**
   * <code>.Chambre chambres = 5;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ChambreOrBuilder getChambresOrBuilder();

  /**
   * <code>string prefrences = 6;</code>
   * @return The prefrences.
   */
  java.lang.String getPrefrences();
  /**
   * <code>string prefrences = 6;</code>
   * @return The bytes for prefrences.
   */
  com.google.protobuf.ByteString
      getPrefrencesBytes();
}
