// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface UpdateClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  ma.ensaj.reservation.grpc.stubs.Client getClient();
  /**
   * <code>.Client client = 1;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
