// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface UpdateChambreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateChambreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Chambre chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   * @return The chambre.
   */
  ma.ensaj.reservation.grpc.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ChambreOrBuilder getChambreOrBuilder();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
