// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.ensaj.reservation.grpc.stubs;

public interface UpdateReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  ma.ensaj.reservation.grpc.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  ma.ensaj.reservation.grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
